### ISSUE TITLE
Where is the repo for the actual Monero V blockchain?

### ISSUE THREAD

**Issue by IAMtheIAM** [monerov/monerov-explorer#2]
Hi, your website links to this repo, the `monerov` collection only has this repo in it. Where would we see the actual code for the monerov blockchain?

**Comment by miltonf** [comment]
More git repos are rolling out. The MoneroV blockchain has not been created yet. There is hard-coded source that obviously can't be published as it contains the seed nodes so the release would be when the blockchain is up and running.
